# Generated by Django 4.0.5 on 2024-02-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fatigue_Detection_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='supervisor_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
