# Generated by Django 4.0.5 on 2024-02-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fatigue_Detection_App', '0002_worker_supervisor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='device_token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
