# Generated by Django 4.0.5 on 2024-02-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fatigue_Detection_App', '0004_alter_worker_device_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='jwt',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
