# Generated by Django 4.0.5 on 2024-02-13 07:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Fatigue_Detection_App', '0005_worker_jwt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fatigue_State',
            fields=[
                ('fatigue_state_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fatigue_state', models.CharField(max_length=20, null=True)),
                ('fatigue_state_created_at', models.DateTimeField(auto_now_add=True)),
                ('fatigue_state_updated_at', models.DateTimeField(auto_now=True)),
                ('fatigue_state_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fatigue_Detection_App.worker')),
            ],
        ),
    ]
