# Generated by Django 4.0.5 on 2024-02-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fatigue_Detection_App', '0006_fatigue_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='last_fatigue_state',
            field=models.DateTimeField(null=True),
        ),
    ]
